name: 'Strip HTML from Markdown'
author: Loïc Denuzière
description: 'Strip HTML content from a Markdown file'
inputs:
  input-path:
    description: 'Path to the markdown file to strip'
    required: true
  output-path:
    description: 'Path to the output markdown file'
    required: false
    default:
  encoding:
    description: 'The file encoding to use'
    required: false
    default: utf8
runs:
  using: 'node12'
  main: 'dist/index.js'